# Load in Numpy


In [1]:
import numpy as np

## The Basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
#Get shape
a.shape

(3,)

In [4]:
#Get size of the array
a.size

3

In [5]:
#Get byte size of each item
a.itemsize

4

In [6]:
#Get total byte size of an array
a.size * a.itemsize

12

In [7]:
#same as above
a.nbytes

12

In [8]:
#Get dimension
a.ndim

1

In [9]:
#intentionally making the elemnets as 2byte
b = np.array([3,4,5], dtype='int16')

In [10]:
b.itemsize

2

In [11]:
b.nbytes

6

## Accessing/Changing specific elements, rows, columns etc.

In [12]:
c = np.array([[1,2,3,4,5,6],[4,5,6,7,8,9]])
c

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [13]:
#get element (work outside in row,col)
c[0,2]

3

In [14]:
#changing that element
c[0,2] = 10
c

array([[ 1,  2, 10,  4,  5,  6],
       [ 4,  5,  6,  7,  8,  9]])

In [15]:
#getting a whole row
c[0, :]

array([ 1,  2, 10,  4,  5,  6])

In [16]:
#getting a whole column
c[:,1]

array([2, 5])

In [17]:
# [startindex,endindex,step]
c[0,1:5:2]

array([2, 4])

In [18]:
c[0,1:5:1]

array([ 2, 10,  4,  5])

In [19]:
#3d example
d = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[6,7,8]]])
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [6, 7, 8]]])

In [20]:
#specifying an element(work outside in)
d[0,0,1]

2

In [21]:
d[1,0,0]

4

In [22]:
d[:,1,:]

array([[4, 5, 6],
       [6, 7, 8]])

In [23]:
d[:,1,:] = [[14,15,16],[16,17,18]]
d

array([[[ 1,  2,  3],
        [14, 15, 16]],

       [[ 4,  5,  6],
        [16, 17, 18]]])

## Initializing diff types of arrays


In [24]:
#zero matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
#ones matriz
np.ones((3,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
#any other number
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [27]:
#any other number using full_like
np.full_like(c,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [28]:
#random decimal number
np.random.rand(4,3)

array([[0.06974654, 0.0128225 , 0.65661189],
       [0.03399693, 0.15107918, 0.51570587],
       [0.19801615, 0.35280458, 0.81188624],
       [0.54863989, 0.17966364, 0.29548361]])

In [29]:
#random int number
np.random.randint(1,5,size=(3,3))

array([[3, 3, 1],
       [1, 4, 4],
       [3, 2, 2]])

In [30]:
#identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
#repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [32]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
#copying arrays
a = np.array([1,2,3])
b = a.copy()
print(b)

[1 2 3]


In [34]:
a = np.array([1,2,3])
a

array([1, 2, 3])

## Mathematics


In [35]:
a = np.array([1,2,3,4,5,6])

In [36]:
a+2

array([3, 4, 5, 6, 7, 8])

In [37]:
a-2

array([-1,  0,  1,  2,  3,  4])

In [38]:
a*2


array([ 2,  4,  6,  8, 10, 12])

In [39]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [40]:
a**2

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [41]:
#Take the sine
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [43]:
#Take the cosine
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

## Linear Algebra

In [50]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [51]:
#Matrix multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [54]:
#find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [57]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np.min(stats)

1

In [59]:
np.max(stats)

6

In [62]:
# axis = 0 --> in each col
np.max(stats,axis=0)

array([4, 5, 6])

In [63]:
# axis = 1 --> in each row
np.max(stats,axis=1)


array([3, 6])

## Reorganizing arrays

In [65]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
after = before.reshape(4,2)
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [72]:
#vertical stacking
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])

np.vstack([v1,v2,v2,v2])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10]])

In [73]:
#Horizontal stacking
h1 = np.array([[1,2],[3,4]])
h2 = np.array([[5,6],[7,8]])

np.hstack([h1,h2])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Miscellaneous and Boolean Masking

## Load data from file

In [78]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

## Boolean Masking

In [79]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])